version: "3.9"

x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  restart: always
  command: server --console-address ":9001" http://minio-prod-{1...2}/data-{1...2}
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    MINIO_BROWSER_REDIRECT_URL: ${CONSOLE_URL}
    MINIO_SERVER_URL: ${MINIO_URL}
  expose:
    - 9000
    - 9001
  networks:
    - internal
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5
  deploy:
    resources:
      limits:
        cpus: ${LIMIT_CPU_APP:-1}
        memory: ${LIMIT_RAM_APP:-256M}
      reservations:
        cpus: "0.2"
        memory: 64M

services:
  app-1:
    <<: *minio-common
    hostname: minio-prod-1
    volumes:
      - ${BASE_VOLUME}/data/data-1-1:/data-1
      - ${BASE_VOLUME}/data/data-1-2:/data-2
  app-2:
    <<: *minio-common
    hostname: minio-prod-2
    volumes:
      - ${BASE_VOLUME}/data/data-2-1:/data-1
      - ${BASE_VOLUME}/data/data-2-2:/data-2
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ${BASE_VOLUME}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 9000
      - 9001
    networks:
      - internal
      - nginx
    depends_on:
      app-1:
        condition: service_started
      app-2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_CPU_NGINX:-0.5}
          memory: ${LIMIT_RAM_NGINX:-256M}
        reservations:
          cpus: "0.1"
          memory: 16M

networks:
  internal:
  nginx:
    external: true
